Fixes for #43 and #61
FRC-1294/scouting-app pull request #64
Opened 2024-02-20 04:10 UTC by MthreeJohnnyK

See #43 and #61.

2024-02-20 06:27 UTC, atian7064 requested changes
Enums should be in all caps.
In addition, the fix for #43 has already been approved. Please remove your changes to ThirdFragment and remember to stick to issues you are assigned to or communicate with the person assigned to work on one pull request.

2024-02-20 06:27 UTC, atian7064 commented on app/src/main/java/com/example/myapplication/SecondFragment2.java
> +
Enums should be in all caps

2024-02-21 03:34 UTC, geeknoid approved these changes

2024-02-22 02:26 UTC, geeknoid approved these changes

2024-02-22 02:27 UTC, atian7064 approved these changes

2024-02-22 02:28 UTC, merged